import { WebSocketGateway, WebSocketServer, SubscribeMessage, OnGatewayConnection, OnGatewayDisconnect, WsException } from '@nestjs/websockets';
import { Server, Socket } from 'socket.io';
import { Channel } from 'src/entities/channel.entity';
import { Message } from 'src/entities/message.entity';
import { User } from 'src/entities/user.entity';

const channelRoomPrefix = "channel_";
const pingTimeout = 60000;

// @WebSocketGateway({transports: [ "websocket" ]})
@WebSocketGateway() 
export class ChatGateway implements OnGatewayConnection, OnGatewayDisconnect {

  @WebSocketServer() private io: Server;

  async handleConnection(client: Socket) {
    const user = await User.findOneBy({ft_login: (client.request as any).user});
    client.data.login = user.ft_login;
    console.log('Websocket Client Connected : ' + user.ft_login);
    user.socket = client.id;
    user.status = User.Status.ONLINE;
    user.save();

    client.data.pingOK = true;
    this.ping(client);
  }

  async handleDisconnect(client: Socket) {
    const user = await User.findOneBy({ft_login: (client.request as any).user});
    console.log('Websocket Client Disconnected : ' + user.ft_login);
    user.socket = null;
    user.status = User.Status.OFFLINE;
    user.save();
  }

  async ping(client: Socket) {
    if (!client.data.pingOK)
      client.disconnect(true);
    else {
      client.data.pingOK = false;
      client.emit('ping');
      setTimeout(() => {
        this.ping(client)
      }, pingTimeout);
    }
  }

  async error(client: Socket, msg: string = ''): Promise<any> {
    client.emit('error', msg);
    return null;
  }

  //  Processes clients ping responses.
  @SubscribeMessage('pong')
  async pong(client: Socket) {
    client.data.pingOK = true;
  }

  //  ********** CORE MESSAGING SERVICE **********

  //  Processes a new message sent by a client (either to a channel or directly to a username)
  //  A Message entity in JSON format is expected as data.
  //
  //  For a direct message, omit channel and set the message <recipient> property as a partial User ( with a user login for example )
  //
  @SubscribeMessage('msg')
  async msg(client: Socket, rawData: string): Promise<Message> {
    try {
      const user = await User.findOneBy({ft_login: client.data.login});
      const data = JSON.parse(rawData);
      data.id = undefined;  //  Supresses the message id to always consider it as a new message.
      data.time = undefined;  //  Supresses the message timestamp to let it be autogenerated.
      data.sender = undefined;  //  Supresses the sender to always consider it as the socket client.
      const message = Message.create(data);
      message.sender = user;
      if (data.channel) {
        message.channel = await Channel.findOne({where: data.channel});
        if (!message.channel) {
          console.log('Message channel was not found !');
          return this.error(client, "Message channel was not found !");
        }
        //  Check if ok to send message to this channel.
        console.log(await message.channel.canSpeak(user));
        if (!message.channel.canSpeak(user))
          return this.error(client, "You cannot speak in this channel !");
        //  Channel message process here.
        return await Message.save(message);
      }
      else if (data.recipient) {
        console.log('direct mode');
        const recipient = await User.findOne({where: data.recipient});
        if (!recipient) {
          console.log('Message recipient was not found !');
          return this.error(client, "Message Recipient was not found !");
        }
        message.channel = await Channel.getDirectChannel(recipient, user, false);
        await message.save();
       // this.io.socket
        message.channel = await Channel.getDirectChannel(user, recipient, true);
        return (message.save());
      }
      else
        return this.error(client, "Invalid message submitted");
    }
    catch (e) {
      this.error(client, e.name + " : " + e.message);
      console.error("[ERROR] " + e.stack)
    }
  }

  @SubscribeMessage('chanlist')
  async chanlist(client: Socket, rawData: string) {
    console.log(JSON.parse(rawData));
  }

  @SubscribeMessage('publiclist')
  async publiclist(client: Socket, rawData: string) {
    console.log(JSON.parse(rawData));
  }

  @SubscribeMessage('userlist')
  async joinedlist(client: Socket, rawData: string) {
    console.log(JSON.parse(rawData));
  }

  @SubscribeMessage('invitelist')
  async invitelist(client: Socket, rawData: string) {
    console.log(JSON.parse(rawData));
  }

  @SubscribeMessage('names')
  async names(client: Socket, rawData: string) {
    console.log(JSON.parse(rawData));
  }

  //  For
  @SubscribeMessage('mode')
  async mode(client: Socket, rawData: string) {
    console.log(JSON.parse(rawData));
  }

}

// @WebSocketGateway(options)
// export class ChatGateway implements OnGatewayConnection{


//   @WebSocketServer()
//   server: Server;

//   // server.in(theSocketId).socketsJoin("room");

//   login_sid_map = new Map();

//   async handleConnection(@ConnectedSocket() socket) {
//     const query = socket.handshake.auth;
//     console.log("User connected");
//     console.log(query);

//     this.login_sid_map.set(query.ft_login, socket.id);
//     console.log(this.login_sid_map.get(query.ft_login));
//     console.log(this.login_sid_map);
//   }

//   @SubscribeMessage('message')
//   async handleMessage(@ConnectedSocket() socket, @MessageBody() data) {
//     const msg = await Message.createMessage(data.login, data.content, data.id);
//     socket.emit('message', {
//       "sender" : msg.sender.username,
//       "content" : msg.content,
//       "time" : msg.time,
//     });
//   }

//   @SubscribeMessage('loadMessages')
//   async loadMessages(@ConnectedSocket() socket, @MessageBody() data) {
//     // fetch Channel corresponding to id
//     const chan = await Channel.findOneBy({
//       id: data.id
//     } as FindOptionsWhere<Channel>);
//     if (chan === null) {
//       console.error("Invalid id : channel with id #%d does not exist.", data.id);
//       return ;
//     }

//     // fetch Message in appropriate channel
//     const messages = await Message.find({
//       relations: { sender: true, channel: true },
//       where: {
//         channel: chan
//       } as FindOptionsWhere<Message>});
//     if (messages === undefined) {
//       console.log("No messages");
//       return ;
//     }

//     // organize data before sending
//     const messagesToSend = messages.map((msg) => {
//       return ({
//         "sender" : msg.sender.username,
//         "content" : msg.content,
//         "time" : msg.time
//       })
//     })

//     socket.emit('loadMessages', messagesToSend);
//   }

//   @SubscribeMessage('getChannels')
//   async getChannel(@ConnectedSocket() socket, @MessageBody() data) {
//     // console.log('debug #2');
//     const chans = await Channel.find();

//     // console.log(data);

//     const user = await User.findByUsername(data.user);
//     const user2 = await User.findByLogin('lratio');
//     const chan = await Channel.findOneBy({name: "#ilovec"});

//     const chansToSend = chans.map((channel) => {
//       return ({
//         "id": channel.id,
//         "name": channel.name,
//         "status": channel.status
//       })
//     })

//     // console.log(chansToSend)

//     socket.emit('getChannels', chansToSend);
//   }
// }


// import { InjectRepository } from '@nestjs/typeorm';
// import {
//   ConnectedSocket,
//   MessageBody,
//   OnGatewayConnection,
//   OnGatewayDisconnect,
//   SubscribeMessage,
//   WebSocketGateway,
//   WebSocketServer
// } from '@nestjs/websockets';
// import { User } from 'src/entities/user.entity';

// const options = {
//   cors: {
//     origin: "*",    // TEMPORARY: BAD PRACTICE
//   }
// }

// @WebSocketGateway(options)
// export class ChatGateway implements OnGatewayConnection, OnGatewayDisconnect {
//   constructor() {}

//   @WebSocketServer() server;
//   @InjectRepository(User) userRep;

//   nbUser: number = 0;

//   messages : object[][] = [];

//   async handleConnection(@ConnectedSocket() socket) {
//     const query = socket.handshake.query;
//     console.log("User connected");
//     this.nbUser++;

//     // await this.chatService.createUser(query.username);
//   }

//   async handleDisconnect(@ConnectedSocket() socket) {
//     const query = socket.handshake.query;
//     console.log("User disconnected");
//     this.nbUser--;

//     // await this.chatService.deleteUser(query.username);
//   }

//   @SubscribeMessage('message')
//   async sendMessage(@ConnectedSocket() socket, @MessageBody() data) {
//     // data.time
//     // data.content
//     // data.sender
//     // data.channel ?

//     console.log(data);
 
//     socket.emit('message', {"user":"bob", "key":12})

//     // const users = await this.chatService.getUser();

//     // socket.emit('message', users);

//     // register in database
//     // emit.to.room(msg)
//   }

//   @SubscribeMessage('getChannels')
//   getChannel(@ConnectedSocket() socket, @MessageBody() data) {
//     console.log("getChannel event fired up");
//     socket.emit('getChannels', [
//       {"id":1, "name":"general", "status":"public"},
//       {"id":2, "name":"private", "status":"private"},
//       {"id":3, "name":"bob", "status":"direct"},
//       {"id":4, "name":"alice", "status":"direct"},
//       {"id":5, "name":"secret", "status":"private"},
//     ]);
//   }

//   @SubscribeMessage('create')
//   createChannel(@MessageBody() data) {
//     // data.sender
//     // data.channel
//     // data.type // public or private
//     // data.password

//     // check chan doesnt already exist // is check necessary
//     // create it
//     // else
//     // return error
//   }

//   @SubscribeMessage('join')
//   joinChannel(@MessageBody() data) {
//     // data.sender // probably cookie/token or sth
//     // data.target // chan name

//     // check if chan exist
//     //    join it (check perms)
//     // emit.to.room(new user just dropped)
//   }

//   @SubscribeMessage('leave')
//   leaveChannel(@MessageBody() data) {
//     // data.sender // probably cookie/token or sth
//     // data.target // chan name

//     //  if chan is now empty, prune it from db
//   }

//   @SubscribeMessage('block')
//   blockUser(@MessageBody() data) {
//     // data.sender // probably cookie/token or sth
//     // data.target // chan name
//     // data.set // true/false to set unset

//     // access db
//   }

//   @SubscribeMessage('ban')
//   banUserFromChan(@MessageBody() data) {
//     // sender name
//     // chanel name
//     // target name
//     // timestamp

//     // if sender is in channel and sender is admin
//     // ban
//   }

//   @SubscribeMessage('mute')
//   muteUserFromChan(@MessageBody() data) {
//     // sender name
//     // chanel name
//     // target name
//     // timestamp

//     // if sender is in channel and sender is admin
//     // mute
//   }

//   @SubscribeMessage('loadMessages')
//   loadMessages(@ConnectedSocket() socket, @MessageBody() data) {
//     // target chan or msg

//     if (this.messages[0] === undefined)
//       this.messages[0] = [];

//     console.log("Loading messages for channel", data);

//     this.messages[0].push({"sender": "bob", "content":"hello", "time": new Date()});

//     console.log(this.messages[0]);
  
//     const key : string = data.toString();
//     socket.emit('loadMessages', [
//       this.messages[0][0],
//       {"sender": "From chan " + key, "content":"hello world !", "time": new Date()},
//       {"sender": "From chan " + key, "content":"hello world !", "time": new Date()},
//       {"sender": "From chan " + key, "content":"hello world !", "time": new Date(25)},
//       {"sender": "From chan " + key, "content":"hello world !", "time": new Date(1000)},
//     ]);

//     // fetch all messages from db
//     // return messages
//   }

//   @SubscribeMessage('setAdmin')
//   setAdmin(@MessageBody() data) {
//     // sender name
//     // channel name
//     // target name
//     // to_set : true/false

//     // if sender is in channel and sender is admin
//     // set/unset
//   }
// }

